enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  datalayer:
    npmAlwaysAuth: true
    npmAuthToken: ghs_f5Ej5YiGoRezyn7rAJQFl48dioe99l1x9AK3
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      js-yaml: "*"
      rimraf: "*"
    peerDependencies:
      nx: "*"
