name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@datalayer'
    - name: Get npm run cache directory path
      id: npm run-cache-dir-path
      run: |
        corepack enable
        npm run set version 3.5.0
        echo "dir=$(npm run config get cacheFolder)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: npm run-cache # use this to check for `cache-hit` (`steps.npm run-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.npm run-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-npm run-${{ hashFiles('**/npm run.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm run-

    - name: Build the package
      run: |
        set -eux
        npm run install
        npm run run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
